apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostvolume-1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /hostvolume-1
